- name: nexus | common
  remote_user: centos
  hosts: nexus
  roles:
    - common
    - firewalld
  tags:
    - common

- name: nexus | docker
  remote_user: centos
  hosts: nexus
  roles:
    - docker-ce
  tags:
    - docker
