---
haproxy_version: 1.8.14
haproxy_port: 9000
haproxy_dir: /etc/haproxy
haproxy_dir_binary: /usr/sbin
haproxy_admin_sock: /run/haproxy_admin.sock
haproxy_stats_user: admin
haproxy_stats_pass: password
haproxy_url_install: https://github.com/jenciso/haproxy-1.8.14.binary.centos7/releases/download/v1.0.0/haproxy-{{ haproxy_version }}.binary.centos7.tar.gz
haproxy_file: "{{ haproxy_url_install | basename }}"
haproxy_ssl_certificate: "{{ vault_haproxy_ssl_certificate }}"

haproxy_config_content: |
  global
      maxconn 4096
      log 127.0.0.1 local0 debug

  defaults
     log global
     option httplog
     option dontlognull
     option forwardfor
     maxconn 60
     timeout connect 5s
     timeout client 5min
     timeout server 5min

  frontend http-in
      bind *:80
      bind *:443 ssl crt /etc/haproxy/ssl/certificate.pem
      mode http
      redirect scheme https if !{ ssl_fc } # Redirect http requests to https
      use_backend nexus

  backend nexus
      server nexus1 127.0.0.1:8081
      mode http
      http-request set-header X-Forwarded-Host %[req.hdr(Host)]
      http-request set-header X-Forwarded-Port %[dst_port]
      http-request add-header X-Forwarded-Proto https if { ssl_fc }
      reqrep ^([^\ :]*)\ /(.*)     \1\ /\2
      acl response-is-redirect res.hdr(Location) -m found
      rspirep ^Location:\ (http)://127.0.0.1:8081/(.*)   Location:\ https://{{ nexus_host }}:443/\2  if response-is-redirect
